#+title: Authsec Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./initl.el :mkdirp yes
#+latex_class: memoir-book

* Introduction

  This =.org= file contains my Emacs configuration for Emacs 27.2+. There is a pretty good guideline on [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#on-macos][the Doom Emacs project]] that tells you which dependencies to install in order to get a proper Emacs installation on your system of choice.

  I am on a Mac and use the =emacs-mac= package from =brew=. It can be installed
  with:

  #+begin_src sh
    # required dependencies
    brew install git ripgrep
    # optional dependencies
    brew install coreutils fd
    # Installs clang
    xcode-select --install
    brew tap railwaycat/emacsmacport
    brew install emacs-mac --with-modules
  #+end_src

  In order to be able to open Emacs from a Spotlight search you need to create a proper alias. A symlink won't show up in Spotlight. Please note that the alias also does not get e very prominent position when using Spotlight.

  You can *either* create the proper alias with the following command:

  #+begin_src sh
    osascript -e 'tell application "Finder" to make alias file to POSIX file "/usr/local/opt/emacs-mac/Emacs.app" at POSIX file "/Applications/"'
  #+end_src

  *or* you simply copy Emacs to the =/Applications= folder like so:

  #+begin_src shell
    cp -r /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app
  #+end_src
  

* Base Configuration

  This is a minimal base configuration for Emacs. 

  #+begin_src emacs-lisp
    (setq inhibit-startup-message t) ;Don't show the start screen
    (setq inhibit-splash-screen t)
    (setq inhibit-startup-message t)
    (setq initial-scratch-message "")

    ;; key bindings
    (when (eq system-type 'darwin) ;; mac specific settings
      (setq mac-command-modifier 'meta) ; Map the command key as the Meta Key, this will give a similar feel on windoze keyboards
      (setq mac-option-modifier 'alt) ;
      (setq mac-right-option-modifier 'none) ; Write accents/umlauts with the right option modifier
      (setq dired-use-ls-dired nil) ; The ls command on MacOS does not support --dired
      )

    (scroll-bar-mode -1) ; Disable the visible scrollbar
    (tool-bar-mode -1)    ; Disable the toolbar
    (tooltip-mode -1)    ; Disable tooltips
    (set-fringe-mode 10) ; Give some breathing room

    (menu-bar-mode -1)   ; Disable the menubar

    (setq visible-bell t); Setup visible bell

    ;; Setup a font
    (set-face-attribute 'default nil :font "PragmataPro" :height 180)

  #+end_src

** Move Backup Files
   Let emacs create backups in a specific directory, mirroring the same folder structure as the original.

   #+begin_src emacs-lisp
     ;; make backup to a designated dir, mirroring the full path

     (defun my-backup-file-name (fpath)
       "Return a new file path of a given file path.
     If the new path's directories does not exist, create them."
       (let* (
	      (backupRootDir "~/.emacs.d/backup/")
	      (filePath (replace-regexp-in-string "[A-Za-z]:" "" fpath )) ; remove Windows driver letter in path, for example, “C:”
	      (backupFilePath (replace-regexp-in-string "//" "/" (concat backupRootDir filePath "~") ))
	      )
	 (make-directory (file-name-directory backupFilePath) (file-name-directory backupFilePath))
	 backupFilePath
	 )
       )

     (setq make-backup-file-name-function 'my-backup-file-name)
   #+end_src
   
   
** Visual Line Mode

   This mode allows long lines to be wrapped if they are too long to fit the current window. The mode can globally be enabled with =global-visual-line-mode= or =visual-line-mode= respectively:

   #+begin_src emacs-lisp
     (global-visual-line-mode t)
   #+end_src
   
** Recent Files
   Emacs can remember recently opened files. After configuring this, you can open recent files with =C-x C-r=.

   #+begin_src emacs-lisp
     (recentf-mode 1)
     (setq recentf-max-menu-items 25)
     (setq recentf-max-saved-items 25)
     (global-set-key "\C-x\ \C-r" 'recentf-open-files)
   #+end_src
   
* Setup Package Management

  Emacs can be extended with more packages. The packages can come from multiple sources, that we have to list in the =init.el= file.

  #+begin_src emacs-lisp
    ;; Initialize package source
    (require 'package)

    (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			     ("Org" . "https://orgmode.org/elpa/")
			     ("elpa" . "https://elpa.gnu.org/packages/")
			     ))

    (package-initialize)
    (unless package-archive-contents (package-refresh-contents))

    ;; initialize use-package
    (unless (package-installed-p 'use-package) (package-install 'use-package))

    (require 'use-package)
    (setq use-package-always-ensure t)

  #+end_src

* Theming

  Emacs has a few basic built in themes, but allows you to package install new themes as well. You can see a few themes on [[https://peach-melpa.org/][Peach Melpa]].
  
  You can setup a basic theme with (not generated into the configuration):

  #+begin_src emacs-lisp :tangle no
    (load-theme 'wombat)
  #+end_src

** Doom Themes

   These themes usually come with =doom-mode= but they do some
   additional configuration for some of the specific modes.

   The =doom-themes= will not be generated into the configuration, it is just for reference and needs to be enabled by removing =:tangle no= from the src block below.

   #+begin_src emacs-lisp :tangle no
     (use-package doom-themes)
   #+end_src

** Solarized

   I do like the solarized themes a lot.

   #+begin_src emacs-lisp
     (use-package solarized-theme)
     (load-theme 'solarized-light t)
   #+end_src

** All The Icons

   This provides a icons for the =doom-modeline=. They may already be installed, but just to make sure, set it up with:

   #+begin_src emacs-lisp
     (use-package all-the-icons
       :if (display-graphic-p)
       :commands all-the-icons-install-fonts
       :init (unless (find-font (font-spec :name "all-the-icons"))
	       (all-the-icons-install-fonts t)))
     (use-package all-the-icons-dired
       :if (display-graphic-p)
       :hook (dired-mode . all-the-icons-dired-mode))

   #+end_src
  
* Show Keybindings

  At first you need to execute the function
  =global-command-log-mode=. After that you can enable the command log
  buffer with =clm/toggle-command-log-buffer= with =M-x=.

  #+begin_src emacs-lisp
    (use-package command-log-mode)
  #+end_src

* Setup a completion framework

  There are =helm= and =ivy=.

  We're setting up =ivy= in this example.

  #+begin_src emacs-lisp
    ;; Install sensible dependencies
    (use-package swiper
      :ensure t
      )
    (use-package counsel
      :ensure t
      :bind (("M-x" . counsel-M-x)
	     ("C-x b" . counsel-ibuffer)
	     ("C-x C-f" . counsel-find-file)
	     :map minibuffer-local-map
	     ("C-r" . 'counsel-minibuffer-history)
	     )
      )
    (use-package ivy
      :diminish
      :bind (("C-s" . swiper)
	     )
      :config
      (ivy-mode 1))
  #+end_src

** ivy-rich

   This will give you the details of the commands when the show in a list.

   #+begin_src emacs-lisp
     (use-package ivy-rich
       :init (ivy-rich-mode 1)
       )
   #+end_src
  
* Modeline

  You can change the modeline to look a bit nicer by using the =doom-modeline= package.

  You can configure it like this:

  #+begin_src emacs-lisp
    (use-package doom-modeline
      :ensure t
      :init (doom-modeline-mode 1)
      :config (setq doom-modeline-height 15) ; Just set this below the fontsize to be as minimal as possible
      )
  #+end_src

* Line Number

  You can turn on line numbers like this:

  #+begin_src emacs-lisp
    ;; enable line numbering
    (column-number-mode)
    (global-display-line-numbers-mode t)

    ;; Disable line numbers for selected modes
    (dolist (mode '(org-mode-hook
		    term-mode-hook
		    eshell-mode-hook))
      (add-hook mode (lambda () (display-line-numbers-mode 0)))
      )
  #+end_src
  
* Rainbow Delimiters

  In order to better differentiate between the various brackets you can color them.

  To enable for all programming modes, use the following
  configuration, where =prog-mode=, the base mode for all programming
  languages, is defined.

  The colors of the brackets are dependent on the theme you are using.

  #+begin_src emacs-lisp
    (use-package rainbow-delimiters
      :hook (prog-mode . rainbow-delimiters-mode))
  #+end_src

* Which Key

  The which key package will show a panel popup when you start typing
  a keybinding, so you can see which keys are available under that.

  You can set up the delay until the popup should be shown with a variable.

  #+begin_src emacs-lisp
    (use-package which-key
      :init (which-key-mode)
      :diminish which-key-mode
      :config
      (setq which-key-idle-delay 0.3)
      )
  #+end_src
  
* Read-Only Buffers 

  You can make a buffer read-only using =C-x C-q=. This is especially good to know if you accidentally hit a key combination and you can no longer type in your buffer.

* General.el

  [[https://github.com/noctuid/general.el][This package]] allows you to conveniently bind keys in emacs. With this you can create a new global command prefix for your own commands.

  You are tring to override an already existing keybinding if you e.g. run into an error like the one shown below. In this case you can either force general to bind the definition or fallback to the key command after a timeout. You can find more information [[https://github.com/noctuid/general.el/blob/master/README.org#how-do-i-prevent-key-sequence-starts-with-non-prefix-key-errors][on general github]]. 
  
  #+begin_example
  (error "Key sequence C-SPC a starts with non-prefix key C-...")
  #+end_example

  Binding Control-Alt-Command-Space as the leader key can be done with the following setup.

  #+begin_src emacs-lisp
    (use-package general
      :config
      (general-create-definer authsec/leader-key
	:prefix "A-C-M-SPC"
	)
      )

    (authsec/leader-key
      "b" 'counsel-bookmark
      "s" 'org-attach-screenshot
      )
  #+end_src

* Hydra

  Hydra allow to set up transient, temporary, keybindings. An example would be to zoom in and out of text with just a single key once you have reached the "sub-menu" with the prefix key chords.

  A simple text zoom example (that you can also reach by default with =C-x C-0=) can be set up like this (not rendered into configuration):

  #+begin_src emacs-lisp :tangle no
    (use-package hydra)
    (defhydra hydra-scale-text (:timeout 4)
      "zoom text"
      ("j" text-scale-increase "in")
      ("k" text-scale-decrease "out")
      ("f" nil "finish" :exit t)
      )

    ;; Bind into my keyspace
    (authsec/leader-key
      "ts" '(hydra-scale-text/body :which-key "zoom text"))
  #+end_src

* Magit

  This is a Emacs frontend for =git= and can be set up with:

  #+begin_src emacs-lisp
    (use-package magit
      :commands (magit-status magit-get-current-branch)
      :custom (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
  #+end_src

* Docker support
  We install =dockerfile-mode= to support docker files.

  #+begin_src emacs-lisp
    (use-package dockerfile-mode)
    (add-to-list 'auto-mode-alist '("Dockerfile\\'" . dockerfile-mode))
  #+end_src

* Org Mode

  Org Mode comes with Emacs, you can however get the latest version from Org ELPA.

  You can make sure the new version is installed with:

  - =org-ellipsis= replaces the '...' characters after a heading when it is folded with the supplied one. The symbol is coming from the =PragmataPro= font, which may not be installed on your system or the site you're viewing this on.
  
  #+begin_src emacs-lisp
    (setq org-display-inline-images t)
    (setq org-redisplay-inline-images t)
    (setq org-startup-with-inline-images "inlineimages")
    (use-package org
      :custom
      (org-ellipsis " ⮷")
      :bind(
	    ("C-c a" . org-agenda)
	    ("C-c c" . org-capture)
	    ("C-c l" . org-store-link)
	    )
      )
  #+end_src
  
** Configure Babel Languages

   To execute or export code in =org-mode= code blocks, you'll need to
   set up =org-babel-load-languages= for each language you'd like to
   use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with
   =org-babel=.

   #+begin_src emacs-lisp
     (with-eval-after-load 'org
       (org-babel-do-load-languages
	'org-babel-load-languages
	'((emacs-lisp . t)
	  (python . t))
	)

       (push '("conf-unix" . conf-unix) org-src-lang-modes))
   #+end_src

*** Org Tempo
    Using =org-tempo= will allow you to quickly create =begin_src..end_src= blocks with a shortcut syntax.

    Using the below setup for example you'd type =<el= and it would render an =emacs-lisp= src block.

    #+begin_src emacs-lisp
      (require 'org-tempo)
      (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
      (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
      (add-to-list 'org-structure-template-alist '("py" . "src python"))
      (add-to-list 'org-structure-template-alist '("java" . "src java"))
    #+end_src

** Org-Bullets

   This package customizes the leading bullets to look a bit nicer.

   #+begin_src emacs-lisp
     (use-package org-bullets
       :after org
       :hook (org-mode . org-bullets-mode))
   #+end_src

** Org Agenda

   In order to track task and e.g. birthdays you can set up org-agenda. This [[https://www.youtube.com/watch?v=PNE-mgkZ6HM&t=5s][Youtube Video]] gives a good overview of the topic.

   #+begin_src emacs-lisp
     (setq org-agenda-files
	   '("~/research/org/tasks.org"))
     (setq org-agenda-start-with-log-mode t)
     (setq org-log-done 'time)
     (setq org-log-into-drawer t)
     (setq org-capture-templates
	   '(("t" "Todo" entry (file+datetree "~/research/org/tasks.org")
	      "* TODO %?\n  %i\n  %a")))

   #+end_src

*** Keywords for TODO states

    You can set up additional states for your tasks by setting up mor todo keywords.
   
    #+begin_src emacs-lisp
      (setq org-todo-keywords
	    '(
	      (sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)")
	      (sequence "CONTACT(c)" "WAITING_FOR_RESPONSE(w)" "|" "DONE(d)")
	      )

	    )
    #+end_src

*** Global Tags

    If you want to use a global tag list, you can configure one like so:
    
    #+begin_src emacs-lisp
      (setq org-tag-alist
	    '((:startgroup)
	      ;; Put mutually exclusive tags here
	      (:endgroup)
	      ("email" . ?e)
	      ("phone" . ?p)
	      ("message" . ?m)
	      )
	    )
    #+end_src

    You can append any of these tags by pressing =C-c C-q= on the line with the TODO item.

**** Project specific tags
     If you do need to set up tags that are required for a specific project, or if you you do want a mechanism where you can append additional tags e.g. at work only, you can use [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][Per-Directory Local Variables]].

     To do that, you simply put a file named =.dir-locals.el= in the directory where you hold your =tasks.org= file. The file can look something like this:

     #+begin_src emacs-lisp :tangle no
       ;; NOT WORKING YET
       (add-to-list 'org-tag-alist

		    '(
		      ("myspecial" . ?M)
		      ("work" . ?w)
		      )

		    )
     #+end_src
    
   
** Org Roam
   =org-roam= aids building a second brain. It basically a implementation of the Zettelkasten note-taking strategy. This allows you to see connections between different notes, that you may not have seen before.

   #+begin_src emacs-lisp
     (setq my-roam-directory (concat (getenv "HOME") "/research/roam-notes"))
     (setq org-roam-v2-ack t)
     (use-package org-roam
       :ensure t
       :custom
       ;; make sure this directory exists
       (org-roam-directory (file-truename my-roam-directory))
       ;; configure the folder where dailies are stored, make sure this exists as well
       (org-roam-dailies-directory "dailies")
       ;; Lets you use completion-at-point
       (org-roam-completion-everywhere t)
       ;; (org-roam-graph-executable "~/bin/dot")
       :bind(
	     ("C-c n l" . org-roam-buffer-toggle)
	     ("C-c n f" . org-roam-node-find)
	     ("C-c n i" . org-roam-node-insert)
	     :map org-mode-map
	     ("C-M-i" . completion-at-point)
	     :map org-roam-dailies-map
	     ("Y" . org-roam-dailies-capture-yesterday)
	     ("T" . org-roam-dailies-capture-tomorrow)
	     )
       :bind-keymap
       ("C-c n d" . org-roam-dailies-map)
       :config
       (require 'org-roam-dailies) ;; Ensure keymap is available
       (org-roam-setup)
       (org-roam-db-autosync-mode)
       )
     ;; Mapping mouse click to preview does not seem to work
     ;;(define-key org-roam-mode-map [mouse-1] #'org-roam-preview-visit)
   #+end_src
   
** Org Roam BibTeX
   [[https://github.com/org-roam/org-roam-bibtex][org-roam-bibtex]] is integrating roam bibtex and org-ref .

   #+begin_src emacs-lisp
     (use-package org-roam-bibtex
       :after org-roam
       :hook (org-roam-mode . org-roam-bibtex-mode)
       :config
       (require 'org-ref)) ; optional: if Org Ref is not loaded anywhere else, load it here
   #+end_src
   
** Org Ref

   =org-ref= helps to manage and insert citations in =org-mode=.
      
   #+begin_src emacs-lisp
     (use-package org-ref
       :after org
       :init
       (setq org-ref-completion-library 'org-ref-ivy-cite)
       :bind (
	      ;; Allows you to create a bibtex entry from a URL like a https:// link
	      ("C-c b i" . org-ref-url-html-to-bibtex)
	      )
       :config
       (setq reftex-default-bibliography '("~/research/bibliography/references.bib"))
       (setq org-ref-bibliography-notes "~/research/bibliography/notes.org")
       (setq org-ref-default-bibliography '("~/research/bibliography/references.bib"))
       (setq org-ref-pdf-directory "~/research/bibliography/bibtex-pdfs/")
       :demand t ;; Demand loading, so links work immediately
       )

   #+end_src
   
** Org Attach Screenshot

   The package [[https://github.com/dfeich/org-screenshot][org-attach-screenshot]] allows you to attach a screenshot into your org document. The below configuration uses the =screencapture= utility found on a Mac. You have to select the screenshot area with the mouse. You may want to tweak this to your setup. 

   #+begin_src emacs-lisp
     (use-package org-attach-screenshot
       :config (setq org-attach-screenshot-dirfunction
		     (lambda () 
		       (progn (cl-assert (buffer-file-name))
			      (concat (file-name-sans-extension (buffer-file-name))
				      "-att")))
		     org-attach-screenshot-command-line "screencapture -i %f"))
     (require 'org-attach-screenshot)
   #+end_src
   
* Deft
  =deft= is a full text search mode that allows you to quickly find your filter expression in a bunch of files.

  You can configure it with:

  #+begin_src emacs-lisp
    (use-package deft
      :config
      (setq deft-directory my-roam-directory
	    deft-recursive t
	    deft-strip-summary-regexp ":PROPERTIES:\n\\(.+\n\\)+:END:\n"
	    deft-use-filename-as-title t)
      :bind
      ("C-c n s" . deft))
  #+end_src
  
* LaTeX Setup
   

  I like to compile latex documents using a docker container I have built. This allows me to just install [[https://www.docker.com/][docker]] and have a consistent build environment accross platforms without having to go through the hassle of having to install e.g. the full tex-live on each and every machine.

  Once I'm done working with latex I can simply delete the container from my system and have everything removed cleanly without leaving a mess or utilizing disk space for nothing.

  The [[https://github.com/authsec/sphinx][authsec/sphinx]] container contains everything needed to properly compile a latex document, as it contains a full tex-live installation amongst other things.

  When exporting from =org-mode= you need to change the latex binary for the export to successfully use the =pdflatex= utility inside the container. You basically supply a list of commands that you want executed to produce the PDF from the =org= file.

  A first approach can look like that:

  #+begin_src emacs-lisp :tangle no
    (setq org-latex-pdf-process
	  (list
	   "docker run --rm -v $\(pwd\):/docs authsec/sphinx pdflatex -interaction nonstopmode -shell-escape %b.tex"
	   "docker run --rm -v $\(pwd\):/docs authsec/sphinx biber %b"
	   "docker run --rm -v $\(pwd\):/docs authsec/sphinx pdflatex -interaction nonstopmode -shell-escape %b.tex"
	   "docker run --rm -v $\(pwd\):/docs authsec/sphinx pdflatex -interaction nonstopmode -shell-escape %b.tex"
	   ))
  #+end_src

  This however will start the container runtime 4 times. This is not particularly bad, but at the same time also not very efficient. So we can optimize this to have the 4 commands executed inside the container by concatenating the commands to run like so (we're also using xelatex here):

  #+begin_src emacs-lisp
    (setq org-latex-pdf-process
	  (list
	   "docker run --rm -v $\(pwd\):/docs authsec/sphinx /bin/sh -c 'pdflatex -interaction nonstopmode -shell-escape %b.tex && biber %b;  pdflatex -interaction nonstopmode -shell-escape %b.tex && pdflatex -interaction nonstopmode -shell-escape %b.tex'"
	   ))
  #+end_src
  
** Source Code Blocks
   To display nice source code blocks you can use the package =minted= which can be set up like this:

   #+begin_src emacs-lisp
     (setq org-latex-listings 'minted
	   org-latex-packages-alist '(("" "minted"))
	   org-latex-minted-options '(("breaklines" "true")
				      ("breakanywhere" "true"))
	   )
   #+end_src

** BibTeX
   Add BibTeX setup for latex.
   
   #+begin_src emacs-lisp
     (use-package ivy-bibtex)

     ;; use the newer biblatex
     (add-to-list 'org-latex-packages-alist '("backend=biber,sortlocale=de" "biblatex"))
   #+end_src

   
   #+begin_src emacs-lisp
     ;;setup dialect to be biblatex as bibtex is quite a bit old
     (setq bibtex-dialect 'biblatex)
     ;; variables that control bibtex key format for auto-generation
     ;; I want firstauthor-year-title-words
     ;; this usually makes a legitimate filename to store pdfs under.
     (setq bibtex-autokey-year-length 4
	   bibtex-autokey-name-year-separator "-"
	   bibtex-autokey-year-title-separator "-"
	   bibtex-autokey-titleword-separator "-"
	   bibtex-autokey-titlewords 2
	   bibtex-autokey-titlewords-stretch 1
	   bibtex-autokey-titleword-length 5)
   #+end_src

** New LaTeX Classes

   If you want to export with a different LaTeX template, you can do this

   #+begin_src emacs-lisp
     (require 'ox-latex)
     (unless (boundp 'org-latex-classes)
       (setq org-latex-classes nil))
   #+end_src

   
*** KOMA Article

    This defines the KOMA scrartcl class and still allows for the previously defined packages to be present.

    #+begin_src emacs-lisp
      (eval-after-load 'ox-latex
	'(add-to-list 'org-latex-classes
		      '("koma-article"
			"\\documentclass{scrartcl}"
			("\\section{%s}" . "\\section*{%s}")
			("\\subsection{%s}" . "\\subsection*{%s}")
			("\\subsubsection{%s}" . "\\subsubsection*{%s}")
			("\\paragraph{%s}" . "\\paragraph*{%s}")
			("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
    #+end_src

*** Memoir Article
    This uses the memoir class as base.

    #+begin_src emacs-lisp
      (eval-after-load 'ox-latex
	'(add-to-list 'org-latex-classes
		      '("memoir-article"
			"\\documentclass[a4paper,10pt,article,oneside]{memoir}"
			("\\chapter{%s}" . "\\chapter*{%s}")
			("\\section{%s}" . "\\section*{%s}")
			("\\subsection{%s}" . "\\subsection*{%s}")       
			("\\subsubsection{%s}" . "\\subsubsection*{%s}")
			("\\paragraph{%s}" . "\\paragraph*{%s}")
			("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
		      ))
    #+end_src

*** Memoir Book

    Use this to set a book.

    #+begin_src emacs-lisp
      (eval-after-load 'ox-latex
	'(add-to-list 'org-latex-classes
		      '("memoir-book"
			"\\documentclass[a4paper,11pt,extrafontsizes,twoside]{memoir}"
			("\\chapter{%s}" . "\\chapter*{%s}")
			("\\section{%s}" . "\\section*{%s}")
			("\\subsection{%s}" . "\\subsection*{%s}")       
			("\\subsubsection{%s}" . "\\subsubsection*{%s}")
			("\\paragraph{%s}" . "\\paragraph*{%s}")
			("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
		      ))
    #+end_src

*** Legrande Book

    Try this.

    #+begin_src emacs-lisp :tangle no
      (eval-after-load 'ox-latex
	'(add-to-list 'org-latex-classes
		      '("book"
			"\\documentclass{book}
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % The Legrand Orange Book
      % Structural Definitions File
      % Version 2.1 \(26/09/2018\)
      %
      % Original author:
      % Mathias Legrand \(legrand.mathias@gmail.com\) with modifications by:
      % Vel \(vel@latextemplates.com\)
      % 
      % This file was downloaded from:
      % http://www.LaTeXTemplates.com
      %
      % License:
      % CC BY-NC-SA 3.0 \(http://creativecommons.org/licenses/by-nc-sa/3.0/\)
      %
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

      %----------------------------------------------------------------------------------------
      %	VARIOUS REQUIRED PACKAGES AND CONFIGURATIONS
      %----------------------------------------------------------------------------------------

      \\usepackage{graphicx} % Required for including pictures
      \\graphicspath{{Pictures/}} % Specifies the directory where pictures are stored

      \\usepackage{lipsum} % Inserts dummy text

      \\usepackage{tikz} % Required for drawing custom shapes

      \\usepackage[english]{babel} % English language/hyphenation

      \\usepackage{enumitem} % Customize lists
      \\setlist{nolistsep} % Reduce spacing between bullet points and numbered lists

      \\usepackage{booktabs} % Required for nicer horizontal rules in tables

      \\usepackage{xcolor} % Required for specifying colors by name
      \\definecolor{ocre}{RGB}{243,102,25} % Define the orange color used for highlighting throughout the book

      %----------------------------------------------------------------------------------------
      %	MARGINS
      %----------------------------------------------------------------------------------------

      \\usepackage{geometry} % Required for adjusting page dimensions and margins

      \\geometry{
	      paper=a4paper, % Paper size, change to letterpaper for US letter size
	      top=3cm, % Top margin
	      bottom=3cm, % Bottom margin
	      left=3cm, % Left margin
	      right=3cm, % Right margin
	      headheight=14pt, % Header height
	      footskip=1.4cm, % Space from the bottom margin to the baseline of the footer
	      headsep=10pt, % Space from the top margin to the baseline of the header
	      %showframe, % Uncomment to show how the type block is set on the page
      }

      %----------------------------------------------------------------------------------------
      %	FONTS
      %----------------------------------------------------------------------------------------

      \\usepackage{avant} % Use the Avantgarde font for headings
      %\\usepackage{times} % Use the Times font for headings
      \\usepackage{mathptmx} % Use the Adobe Times Roman as the default text font together with math symbols from the Sym­bol, Chancery and Com­puter Modern fonts

      \\usepackage{microtype} % Slightly tweak font spacing for aesthetics
      \\usepackage[utf8]{inputenc} % Required for including letters with accents
      \\usepackage[T1]{fontenc} % Use 8-bit encoding that has 256 glyphs

      %----------------------------------------------------------------------------------------
      %	BIBLIOGRAPHY AND INDEX
      %----------------------------------------------------------------------------------------

      \\usepackage[style=numeric,citestyle=numeric,sorting=nyt,sortcites=true,autopunct=true,babel=hyphen,hyperref=true,abbreviate=false,backref=true,backend=biber]{biblatex}
      \\addbibresource{bibliography.bib} % BibTeX bibliography file
      \\defbibheading{bibempty}{}

      \\usepackage{calc} % For simpler calculation - used for spacing the index letter headings correctly
      \\usepackage{makeidx} % Required to make an index
      \\makeindex % Tells LaTeX to create the files required for indexing

      %----------------------------------------------------------------------------------------
      %	MAIN TABLE OF CONTENTS
      %----------------------------------------------------------------------------------------

      \\usepackage{titletoc} % Required for manipulating the table of contents

      \\contentsmargin{0cm} % Removes the default margin

      % Part text styling \(this is mostly taken care of in the PART HEADINGS section of this file\)
      \\titlecontents{part}
	      [0cm] % Left indentation
	      {\\addvspace{20pt}\\bfseries} % Spacing and font options for parts
	      {}
	      {}
	      {}

      % Chapter text styling
      \\titlecontents{chapter}
	      [1.25cm] % Left indentation
	      {\\addvspace{12pt}\\large\\sffamily\\bfseries} % Spacing and font options for chapters
	      {\\color{ocre!60}\\contentslabel[\\Large\\thecontentslabel]{1.25cm}\\color{ocre}} % Formatting of numbered sections of this type
	      {\\color{ocre}} % Formatting of numberless sections of this type
	      {\\color{ocre!60}\\normalsize\\\;\\titlerule*[.5pc]{.}\\\;\\thecontentspage} % Formatting of the filler to the right of the heading and the page number

      % Section text styling
      \\titlecontents{section}
	      [1.25cm] % Left indentation
	      {\\addvspace{3pt}\\sffamily\\bfseries} % Spacing and font options for sections
	      {\\contentslabel[\\thecontentslabel]{1.25cm}} % Formatting of numbered sections of this type
	      {} % Formatting of numberless sections of this type
	      {\\hfill\\color{black}\\thecontentspage} % Formatting of the filler to the right of the heading and the page number

      % Subsection text styling
      \\titlecontents{subsection}
	      [1.25cm] % Left indentation
	      {\\addvspace{1pt}\\sffamily\\small} % Spacing and font options for subsections
	      {\\contentslabel[\\thecontentslabel]{1.25cm}} % Formatting of numbered sections of this type
	      {} % Formatting of numberless sections of this type
	      {\\ \\titlerule*[.5pc]{.}\\\;\\thecontentspage} % Formatting of the filler to the right of the heading and the page number

      % Figure text styling
      \\titlecontents{figure}
	      [1.25cm] % Left indentation
	      {\\addvspace{1pt}\\sffamily\\small} % Spacing and font options for figures
	      {\\thecontentslabel\\hspace*{1em}} % Formatting of numbered sections of this type
	      {} % Formatting of numberless sections of this type
	      {\\ \\titlerule*[.5pc]{.}\\\;\\thecontentspage} % Formatting of the filler to the right of the heading and the page number

      % Table text styling
      \\titlecontents{table}
	      [1.25cm] % Left indentation
	      {\\addvspace{1pt}\\sffamily\\small} % Spacing and font options for tables
	      {\\thecontentslabel\\hspace*{1em}} % Formatting of numbered sections of this type
	      {} % Formatting of numberless sections of this type
	      {\\ \\titlerule*[.5pc]{.}\\\;\\thecontentspage} % Formatting of the filler to the right of the heading and the page number

      %----------------------------------------------------------------------------------------
      %	MINI TABLE OF CONTENTS IN PART HEADS
      %----------------------------------------------------------------------------------------

      % Chapter text styling
      \\titlecontents{lchapter}
	      [0em] % Left indentation
	      {\\addvspace{15pt}\\large\\sffamily\\bfseries} % Spacing and font options for chapters
	      {\\color{ocre}\\contentslabel[\\Large\\thecontentslabel]{1.25cm}\\color{ocre}} % Chapter number
	      {}  
	      {\\color{ocre}\\normalsize\\sffamily\\bfseries\\\;\\titlerule*[.5pc]{.}\\\;\\thecontentspage} % Page number

      % Section text styling
      \\titlecontents{lsection}
	      [0em] % Left indentation
	      {\\sffamily\\small} % Spacing and font options for sections
	      {\\contentslabel[\\thecontentslabel]{1.25cm}} % Section number
	      {}
	      {}

      % Subsection text styling \(note these aren't shown by default, display them by searchings this file for tocdepth and reading the commented text\)
      \\titlecontents{lsubsection}
	      [.5em] % Left indentation
	      {\\sffamily\\footnotesize} % Spacing and font options for subsections
	      {\\contentslabel[\\thecontentslabel]{1.25cm}}
	      {}
	      {}

      %----------------------------------------------------------------------------------------
      %	HEADERS AND FOOTERS
      %----------------------------------------------------------------------------------------

      \\usepackage{fancyhdr} % Required for header and footer configuration

      \\pagestyle{fancy} % Enable the custom headers and footers

      \\renewcommand{\\chaptermark}[1]{\\markboth{\\sffamily\\normalsize\\bfseries\\chaptername\\ \\thechapter.\\ #1}{}} % Styling for the current chapter in the header
      \\renewcommand{\\sectionmark}[1]{\\markright{\\sffamily\\normalsize\\thesection\\hspace{5pt}#1}{}} % Styling for the current section in the header

      \\fancyhf{} % Clear default headers and footers
      \\fancyhead[LE,RO]{\\sffamily\\normalsize\\thepage} % Styling for the page number in the header
      \\fancyhead[LO]{\\rightmark} % Print the nearest section name on the left side of odd pages
      \\fancyhead[RE]{\\leftmark} % Print the current chapter name on the right side of even pages
      %\\fancyfoot[C]{\\thepage} % Uncomment to include a footer

      \\renewcommand{\\headrulewidth}{0.5pt} % Thickness of the rule under the header

      \\fancypagestyle{plain}{% Style for when a plain pagestyle is specified
	      \\fancyhead{}\\renewcommand{\\headrulewidth}{0pt}%
      }

      % Removes the header from odd empty pages at the end of chapters
      \\makeatletter
      \\renewcommand{\\cleardoublepage}{
      \\clearpage\\ifodd\\c@page\\else
      \\hbox{}
      \\vspace*{\\fill}
      \\thispagestyle{empty}
      \\newpage
      \\fi}

      %----------------------------------------------------------------------------------------
      %	THEOREM STYLES
      %----------------------------------------------------------------------------------------

      \\usepackage{amsmath,amsfonts,amssymb,amsthm} % For math equations, theorems, symbols, etc

      \\newcommand{\\intoo}[2]{\\mathopen{]}#1\\,\;#2\\mathclose{[}}
      \\newcommand{\\ud}{\\mathop{\\mathrm{{}d}}\\mathopen{}}
      \\newcommand{\\intff}[2]{\\mathopen{[}#1\\,\;#2\\mathclose{]}}
      \\renewcommand{\\qedsymbol}{$\\blacksquare$}
      \\newtheorem{notation}{Notation}[chapter]

      % Boxed/framed environments
      \\newtheoremstyle{ocrenumbox}% Theorem style name
      {0pt}% Space above
      {0pt}% Space below
      {\\normalfont}% Body font
      {}% Indent amount
      {\\small\\bf\\sffamily\\color{ocre}}% Theorem head font
      {\\\;}% Punctuation after theorem head
      {0.25em}% Space after theorem head
      {\\small\\sffamily\\color{ocre}\\thmname{#1}\\nobreakspace\\thmnumber{\\@ifnotempty{#1}{}\\@upn{#2}}% Theorem text \(e.g. Theorem 2.1\)
      \\thmnote{\\nobreakspace\\the\\thm@notefont\\sffamily\\bfseries\\color{black}---\\nobreakspace#3.}} % Optional theorem note

      \\newtheoremstyle{blacknumex}% Theorem style name
      {5pt}% Space above
      {5pt}% Space below
      {\\normalfont}% Body font
      {} % Indent amount
      {\\small\\bf\\sffamily}% Theorem head font
      {\\\;}% Punctuation after theorem head
      {0.25em}% Space after theorem head
      {\\small\\sffamily{\\tiny\\ensuremath{\\blacksquare}}\\nobreakspace\\thmname{#1}\\nobreakspace\\thmnumber{\\@ifnotempty{#1}{}\\@upn{#2}}% Theorem text \(e.g. Theorem 2.1\)
      \\thmnote{\\nobreakspace\\the\\thm@notefont\\sffamily\\bfseries---\\nobreakspace#3.}}% Optional theorem note

      \\newtheoremstyle{blacknumbox} % Theorem style name
      {0pt}% Space above
      {0pt}% Space below
      {\\normalfont}% Body font
      {}% Indent amount
      {\\small\\bf\\sffamily}% Theorem head font
      {\\\;}% Punctuation after theorem head
      {0.25em}% Space after theorem head
      {\\small\\sffamily\\thmname{#1}\\nobreakspace\\thmnumber{\\@ifnotempty{#1}{}\\@upn{#2}}% Theorem text \(e.g. Theorem 2.1\)
      \\thmnote{\\nobreakspace\\the\\thm@notefont\\sffamily\\bfseries---\\nobreakspace#3.}}% Optional theorem note

      % Non-boxed/non-framed environments
      \\newtheoremstyle{ocrenum}% Theorem style name
      {5pt}% Space above
      {5pt}% Space below
      {\\normalfont}% Body font
      {}% Indent amount
      {\\small\\bf\\sffamily\\color{ocre}}% Theorem head font
      {\\\;}% Punctuation after theorem head
      {0.25em}% Space after theorem head
      {\\small\\sffamily\\color{ocre}\\thmname{#1}\\nobreakspace\\thmnumber{\\@ifnotempty{#1}{}\\@upn{#2}}% Theorem text \(e.g. Theorem 2.1\)
      \\thmnote{\\nobreakspace\\the\\thm@notefont\\sffamily\\bfseries\\color{black}---\\nobreakspace#3.}} % Optional theorem note
      \\makeatother

      % Defines the theorem text style for each type of theorem to one of the three styles above
      \\newcounter{dummy} 
      \\numberwithin{dummy}{section}
      \\theoremstyle{ocrenumbox}
      \\newtheorem{theoremeT}[dummy]{Theorem}
      \\newtheorem{problem}{Problem}[chapter]
      \\newtheorem{exerciseT}{Exercise}[chapter]
      \\theoremstyle{blacknumex}
      \\newtheorem{exampleT}{Example}[chapter]
      \\theoremstyle{blacknumbox}
      \\newtheorem{vocabulary}{Vocabulary}[chapter]
      \\newtheorem{definitionT}{Definition}[section]
      \\newtheorem{corollaryT}[dummy]{Corollary}
      \\theoremstyle{ocrenum}
      \\newtheorem{proposition}[dummy]{Proposition}

      %----------------------------------------------------------------------------------------
      %	DEFINITION OF COLORED BOXES
      %----------------------------------------------------------------------------------------

      \\RequirePackage[framemethod=default]{mdframed} % Required for creating the theorem, definition, exercise and corollary boxes

      % Theorem box
      \\newmdenv[skipabove=7pt,
      skipbelow=7pt,
      backgroundcolor=black!5,
      linecolor=ocre,
      innerleftmargin=5pt,
      innerrightmargin=5pt,
      innertopmargin=5pt,
      leftmargin=0cm,
      rightmargin=0cm,
      innerbottommargin=5pt]{tBox}

      % Exercise box	  
      \\newmdenv[skipabove=7pt,
      skipbelow=7pt,
      rightline=false,
      leftline=true,
      topline=false,
      bottomline=false,
      backgroundcolor=ocre!10,
      linecolor=ocre,
      innerleftmargin=5pt,
      innerrightmargin=5pt,
      innertopmargin=5pt,
      innerbottommargin=5pt,
      leftmargin=0cm,
      rightmargin=0cm,
      linewidth=4pt]{eBox}	

      % Definition box
      \\newmdenv[skipabove=7pt,
      skipbelow=7pt,
      rightline=false,
      leftline=true,
      topline=false,
      bottomline=false,
      linecolor=ocre,
      innerleftmargin=5pt,
      innerrightmargin=5pt,
      innertopmargin=0pt,
      leftmargin=0cm,
      rightmargin=0cm,
      linewidth=4pt,
      innerbottommargin=0pt]{dBox}	

      % Corollary box
      \\newmdenv[skipabove=7pt,
      skipbelow=7pt,
      rightline=false,
      leftline=true,
      topline=false,
      bottomline=false,
      linecolor=gray,
      backgroundcolor=black!5,
      innerleftmargin=5pt,
      innerrightmargin=5pt,
      innertopmargin=5pt,
      leftmargin=0cm,
      rightmargin=0cm,
      linewidth=4pt,
      innerbottommargin=5pt]{cBox}

      % Creates an environment for each type of theorem and assigns it a theorem text style from the "Theorem Styles" section above and a colored box from above
      \\newenvironment{theorem}{\\begin{tBox}\\begin{theoremeT}}{\\end{theoremeT}\\end{tBox}}
      \\newenvironment{exercise}{\\begin{eBox}\\begin{exerciseT}}{\\hfill{\\color{ocre}\\tiny\\ensuremath{\\blacksquare}}\\end{exerciseT}\\end{eBox}}				  
      \\newenvironment{definition}{\\begin{dBox}\\begin{definitionT}}{\\end{definitionT}\\end{dBox}}	
      \\newenvironment{example}{\\begin{exampleT}}{\\hfill{\\tiny\\ensuremath{\\blacksquare}}\\end{exampleT}}		
      \\newenvironment{corollary}{\\begin{cBox}\\begin{corollaryT}}{\\end{corollaryT}\\end{cBox}}	

      %----------------------------------------------------------------------------------------
      %	REMARK ENVIRONMENT
      %----------------------------------------------------------------------------------------

      \\newenvironment{remark}{\\par\\vspace{10pt}\\small % Vertical white space above the remark and smaller font size
      \\begin{list}{}{
      \\leftmargin=35pt % Indentation on the left
      \\rightmargin=25pt}\\item\\ignorespaces % Indentation on the right
      \\makebox[-2.5pt]{\\begin{tikzpicture}[overlay]
      \\node[draw=ocre!60,line width=1pt,circle,fill=ocre!25,font=\\sffamily\\bfseries,inner sep=2pt,outer sep=0pt] at \(-15pt,0pt\){\\textcolor{ocre}{R}}\;\\end{tikzpicture}} % Orange R in a circle
      \\advance\\baselineskip -1pt}{\\end{list}\\vskip5pt} % Tighter line spacing and white space after remark

      %----------------------------------------------------------------------------------------
      %	SECTION NUMBERING IN THE MARGIN
      %----------------------------------------------------------------------------------------

      \\makeatletter
      \\renewcommand{\\@seccntformat}[1]{\\llap{\\textcolor{ocre}{\\csname the#1\\endcsname}\\hspace{1em}}}                    
      \\renewcommand{\\section}{\\@startsection{section}{1}{\\z@}
      {-4ex \\@plus -1ex \\@minus -.4ex}
      {1ex \\@plus.2ex }
      {\\normalfont\\large\\sffamily\\bfseries}}
      \\renewcommand{\\subsection}{\\@startsection {subsection}{2}{\\z@}
      {-3ex \\@plus -0.1ex \\@minus -.4ex}
      {0.5ex \\@plus.2ex }
      {\\normalfont\\sffamily\\bfseries}}
      \\renewcommand{\\subsubsection}{\\@startsection {subsubsection}{3}{\\z@}
      {-2ex \\@plus -0.1ex \\@minus -.2ex}
      {.2ex \\@plus.2ex }
      {\\normalfont\\small\\sffamily\\bfseries}}                        
      \\renewcommand\\paragraph{\\@startsection{paragraph}{4}{\\z@}
      {-2ex \\@plus-.2ex \\@minus .2ex}
      {.1ex}
      {\\normalfont\\small\\sffamily\\bfseries}}

      %----------------------------------------------------------------------------------------
      %	PART HEADINGS
      %----------------------------------------------------------------------------------------

      % Numbered part in the table of contents
      \\newcommand{\\@mypartnumtocformat}[2]{%
	      \\setlength\\fboxsep{0pt}%
	      \\noindent\\colorbox{ocre!20}{\\strut\\parbox[c][.7cm]{\\ecart}{\\color{ocre!70}\\Large\\sffamily\\bfseries\\centering#1}}\\hskip\\esp\\colorbox{ocre!40}{\\strut\\parbox[c][.7cm]{\\linewidth-\\ecart-\\esp}{\\Large\\sffamily\\centering#2}}%
      }

      % Unnumbered part in the table of contents
      \\newcommand{\\@myparttocformat}[1]{%
	      \\setlength\\fboxsep{0pt}%
	      \\noindent\\colorbox{ocre!40}{\\strut\\parbox[c][.7cm]{\\linewidth}{\\Large\\sffamily\\centering#1}}%
      }

      \\newlength\\esp
      \\setlength\\esp{4pt}
      \\newlength\\ecart
      \\setlength\\ecart{1.2cm-\\esp}
      \\newcommand{\\thepartimage}{}%
      \\newcommand{\\partimage}[1]{\\renewcommand{\\thepartimage}{#1}}%
      \\def\\@part[#1]#2{%
      \\ifnum \\c@secnumdepth >-2\\relax%
      \\refstepcounter{part}%
      \\addcontentsline{toc}{part}{\\texorpdfstring{\\protect\\@mypartnumtocformat{\\thepart}{#1}}{\\partname~\\thepart\\ ---\\ #1}}
      \\else%
      \\addcontentsline{toc}{part}{\\texorpdfstring{\\protect\\@myparttocformat{#1}}{#1}}%
      \\fi%
      \\startcontents%
      \\markboth{}{}%
      {\\thispagestyle{empty}%
      \\begin{tikzpicture}[remember picture,overlay]%
      \\node at \(current page.north west\){\\begin{tikzpicture}[remember picture,overlay]%	
      \\fill[ocre!20]\(0cm,0cm\) rectangle \(\\paperwidth,-\\paperheight\)\;
      \\node[anchor=north] at \(4cm,-3.25cm\){\\color{ocre!40}\\fontsize{220}{100}\\sffamily\\bfseries\\thepart}\; 
      \\node[anchor=south east] at \(\\paperwidth-1cm,-\\paperheight+1cm\){\\parbox[t][][t]{8.5cm}{
      \\printcontents{l}{0}{\\setcounter{tocdepth}{1}}% The depth to which the Part mini table of contents displays headings\; 0 for chapters only, 1 for chapters and sections and 2 for chapters, sections and subsections
      }}\;
      \\node[anchor=north east] at \(\\paperwidth-1.5cm,-3.25cm\){\\parbox[t][][t]{15cm}{\\strut\\raggedleft\\color{white}\\fontsize{30}{30}\\sffamily\\bfseries#2}}\;
      \\end{tikzpicture}}\;
      \\end{tikzpicture}}%
      \\@endpart}
      \\def\\@spart#1{%
      \\startcontents%
      \\phantomsection
      {\\thispagestyle{empty}%
      \\begin{tikzpicture}[remember picture,overlay]%
      \\node at \(current page.north west\){\\begin{tikzpicture}[remember picture,overlay]%	
      \\fill[ocre!20]\(0cm,0cm\) rectangle \(\\paperwidth,-\\paperheight\)\;
      \\node[anchor=north east] at \(\\paperwidth-1.5cm,-3.25cm\){\\parbox[t][][t]{15cm}{\\strut\\raggedleft\\color{white}\\fontsize{30}{30}\\sffamily\\bfseries#1}}\;
      \\end{tikzpicture}}\;
      \\end{tikzpicture}}
      \\addcontentsline{toc}{part}{\\texorpdfstring{%
      \\setlength\\fboxsep{0pt}%
      \\noindent\\protect\\colorbox{ocre!40}{\\strut\\protect\\parbox[c][.7cm]{\\linewidth}{\\Large\\sffamily\\protect\\centering #1\\quad\\mbox{}}}}{#1}}%
      \\@endpart}
      \\def\\@endpart{\\vfil\\newpage
      \\if@twoside
      \\if@openright
      \\null
      \\thispagestyle{empty}%
      \\newpage
      \\fi
      \\fi
      \\if@tempswa
      \\twocolumn
      \\fi}

      %----------------------------------------------------------------------------------------
      %	CHAPTER HEADINGS
      %----------------------------------------------------------------------------------------

      % A switch to conditionally include a picture, implemented by Christian Hupfer
      \\newif\\ifusechapterimage
      \\usechapterimagetrue
      \\newcommand{\\thechapterimage}{}%
      \\newcommand{\\chapterimage}[1]{\\ifusechapterimage\\renewcommand{\\thechapterimage}{#1}\\fi}%
      \\newcommand{\\autodot}{.}
      \\def\\@makechapterhead#1{%
      {\\parindent \\z@ \\raggedright \\normalfont
      \\ifnum \\c@secnumdepth >\\m@ne
      \\if@mainmatter
      \\begin{tikzpicture}[remember picture,overlay]
      \\node at \(current page.north west\)
      {\\begin{tikzpicture}[remember picture,overlay]
      \\node[anchor=north west,inner sep=0pt] at \(0,0\) {\\ifusechapterimage\\includegraphics[width=\\paperwidth]{\\thechapterimage}\\fi}\;
      \\draw[anchor=west] \(\\Gm@lmargin,-9cm\) node [line width=2pt,rounded corners=15pt,draw=ocre,fill=white,fill opacity=0.5,inner sep=15pt]{\\strut\\makebox[22cm]{}}\;
      \\draw[anchor=west] \(\\Gm@lmargin+.3cm,-9cm\) node {\\huge\\sffamily\\bfseries\\color{black}\\thechapter\\autodot~#1\\strut}\;
      \\end{tikzpicture}}\;
      \\end{tikzpicture}
      \\else
      \\begin{tikzpicture}[remember picture,overlay]
      \\node at \(current page.north west\)
      {\\begin{tikzpicture}[remember picture,overlay]
      \\node[anchor=north west,inner sep=0pt] at \(0,0\) {\\ifusechapterimage\\includegraphics[width=\\paperwidth]{\\thechapterimage}\\fi}\;
      \\draw[anchor=west] \(\\Gm@lmargin,-9cm\) node [line width=2pt,rounded corners=15pt,draw=ocre,fill=white,fill opacity=0.5,inner sep=15pt]{\\strut\\makebox[22cm]{}}\;
      \\draw[anchor=west] \(\\Gm@lmargin+.3cm,-9cm\) node {\\huge\\sffamily\\bfseries\\color{black}#1\\strut}\;
      \\end{tikzpicture}}\;
      \\end{tikzpicture}
      \\fi\\fi\\par\\vspace*{270\\p@}}}

      %-------------------------------------------

      \\def\\@makeschapterhead#1{%
      \\begin{tikzpicture}[remember picture,overlay]
      \\node at \(current page.north west\)
      {\\begin{tikzpicture}[remember picture,overlay]
      \\node[anchor=north west,inner sep=0pt] at \(0,0\) {\\ifusechapterimage\\includegraphics[width=\\paperwidth]{\\thechapterimage}\\fi}\;
      \\draw[anchor=west] \(\\Gm@lmargin,-9cm\) node [line width=2pt,rounded corners=15pt,draw=ocre,fill=white,fill opacity=0.5,inner sep=15pt]{\\strut\\makebox[22cm]{}}\;
      \\draw[anchor=west] \(\\Gm@lmargin+.3cm,-9cm\) node {\\huge\\sffamily\\bfseries\\color{black}#1\\strut}\;
      \\end{tikzpicture}}\;
      \\end{tikzpicture}
      \\par\\vspace*{270\\p@}}
      \\makeatother

      %----------------------------------------------------------------------------------------
      %	LINKS
      %----------------------------------------------------------------------------------------

      \\usepackage{hyperref}
      \\hypersetup{hidelinks\,backref=true\,pagebackref=true\,hyperindex=true\,colorlinks=false\,breaklinks=true\,urlcolor=ocre\,bookmarks=true\,bookmarksopen=false}

      \\usepackage{bookmark}
      \\bookmarksetup{
      open\,
      numbered\,
      addtohook={%
      \\ifnum\\bookmarkget{level}=0 % chapter
      \\bookmarksetup{bold}%
      \\fi
      \\ifnum\\bookmarkget{level}=-1 % part
      \\bookmarksetup{color=ocre\,bold}%
      \\fi
      }
      }

      [NO-DEFAULT-PACKAGES]
      [NO-PACKAGES]
      "
			("\\part{%s}" . "\\part*{%s}")
			("\\chapter{%s}" . "\\chapter*{%s}")
			("\\section{%s}" . "\\section*{%s}")
			("\\subsection{%s}" . "\\subsection*{%s}")
			("\\subsubsection{%s}" . "\\subsubsection*{%s}")
			("\\paragraph{%s}" . "\\paragraph*{%s}")
			("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
    #+end_src


    
* Git Integration

  If you might want to store your documents in a =git= repository you can use [[https://github.com/ryuslash/git-auto-commit-mode][Git Auto Commit Mode]] to automatically commit your document to a predefined git repository.

  #+begin_src emacs-lisp
    (use-package git-auto-commit-mode) 
  #+end_src
